# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\'\n\tkey_value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x03key\x12\x0b\n\x03key\x18\x01 \x01(\t\"]\n\rvoter_details\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrent_term\x18\x02 \x01(\x05\x12\x12\n\nlog_length\x18\x03 \x01(\x05\x12\x11\n\tlast_term\x18\x04 \x01(\x05\"\xb5\x01\n\x0eleader_details\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x12\n\nprefix_len\x18\x03 \x01(\x05\x12\x13\n\x0bprefix_term\x18\x04 \x01(\x05\x12\x15\n\rleader_commit\x18\x05 \x01(\x05\x12\x1f\n\x06suffix\x18\x06 \x03(\x0b\x32\x0f.raft.log_entry\x12\r\n\x05no_op\x18\x07 \x01(\t\x12\x12\n\nlease_time\x18\x08 \x01(\x02\"5\n\tlog_entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\"T\n\x0evoter_response\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07granted\x18\x03 \x01(\x08\x12\x12\n\nlease_time\x18\x04 \x01(\x02\"J\n\x0clog_response\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\x08\"B\n\x0fserver_response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2P\n\x11\x43\x61ndidateFunction\x12;\n\x0cvote_request\x12\x13.raft.voter_details\x1a\x14.raft.voter_response\"\x00\x32v\n\x0e\x43lientFunction\x12\x34\n\x08set_pair\x12\x0f.raft.key_value\x1a\x15.raft.server_response\"\x00\x12.\n\x08get_pair\x12\t.raft.key\x1a\x15.raft.server_response\"\x00\x32K\n\x0eLeaderFunction\x12\x39\n\x0blog_request\x12\x14.raft.leader_details\x1a\x12.raft.log_response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEY_VALUE']._serialized_start=20
  _globals['_KEY_VALUE']._serialized_end=59
  _globals['_KEY']._serialized_start=61
  _globals['_KEY']._serialized_end=79
  _globals['_VOTER_DETAILS']._serialized_start=81
  _globals['_VOTER_DETAILS']._serialized_end=174
  _globals['_LEADER_DETAILS']._serialized_start=177
  _globals['_LEADER_DETAILS']._serialized_end=358
  _globals['_LOG_ENTRY']._serialized_start=360
  _globals['_LOG_ENTRY']._serialized_end=413
  _globals['_VOTER_RESPONSE']._serialized_start=415
  _globals['_VOTER_RESPONSE']._serialized_end=499
  _globals['_LOG_RESPONSE']._serialized_start=501
  _globals['_LOG_RESPONSE']._serialized_end=575
  _globals['_SERVER_RESPONSE']._serialized_start=577
  _globals['_SERVER_RESPONSE']._serialized_end=643
  _globals['_CANDIDATEFUNCTION']._serialized_start=645
  _globals['_CANDIDATEFUNCTION']._serialized_end=725
  _globals['_CLIENTFUNCTION']._serialized_start=727
  _globals['_CLIENTFUNCTION']._serialized_end=845
  _globals['_LEADERFUNCTION']._serialized_start=847
  _globals['_LEADERFUNCTION']._serialized_end=922
# @@protoc_insertion_point(module_scope)
